name: DefendTheVillage
version: 1.1b
autors: [odarriba] 
main: com.asturcraft.defendTheVillage.Main
softdepend: [Multiverse-Core]
depend: [ForceRespawn]
commands:
  vd:
    description: Minigame of Defend The Village.
    aliases: [villagedefence, villagedef]
  abandonar:
    description: Left the arena.